### ISSUE TITLE
[feat] Context Api 생성, Todo 추가 기능

### ISSUE THREAD

**Issue by senasoon** [senasoon/wanted-pre-onboarding-week4-assignment#7]
# Description
- [x] search Context 생성
- [x] search item 클릭 시 Todo 추가 기능
- [x] 검색어 선택 시 input 초기화
